CREATE TABLE "suppliers" (
	"id_suppliers" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"price_services" INTEGER NOT NULL UNIQUE,
	"company_name" VARCHAR NOT NULL UNIQUE,
	PRIMARY KEY("id_suppliers")
);


CREATE TABLE "purchase_order" (
	"id_order" INTEGER NOT NULL UNIQUE,
	"id_suppliers" INTEGER NOT NULL,
	"id_composition" INTEGER NOT NULL,
	"cost_delivery_value " INTEGER NOT NULL,
	"payment_method" VARCHAR NOT NULL,
	PRIMARY KEY("id_order")
);


CREATE TABLE "products" (
	"id_products" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name_product" VARCHAR NOT NULL UNIQUE,
	"quantity_in_warehouse" INTEGER,
	PRIMARY KEY("id_products")
);


CREATE TABLE "products_recipes" (
	"id_products" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_recipes" INTEGER NOT NULL UNIQUE,
	"quantity_for_recipe" INTEGER NOT NULL,
	PRIMARY KEY("id_products", "id_recipes")
);


CREATE TABLE "recipes" (
	"id_recipes" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name_recipes" VARCHAR NOT NULL UNIQUE,
	"cooking_time" TIME NOT NULL,
	PRIMARY KEY("id_recipes")
);


CREATE TABLE "dishes" (
	"id_dish" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_recipes" INTEGER NOT NULL UNIQUE,
	"category" VARCHAR NOT NULL,
	"name_dish" VARCHAR NOT NULL UNIQUE,
	PRIMARY KEY("id_dish")
);


CREATE TABLE "dishes_menu" (
	"id_dish" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"Id_menu" INTEGER NOT NULL UNIQUE,
	"price" INTEGER NOT NULL,
	PRIMARY KEY("id_dish", "Id_menu")
);


CREATE TABLE "menu" (
	"id_menu" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"date_of_establishment" DATE NOT NULL,
	PRIMARY KEY("id_menu")
);


CREATE TABLE "user" (
	"id_user" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR NOT NULL,
	"pass_hash" INTEGER NOT NULL UNIQUE,
	"role" VARCHAR NOT NULL,
	PRIMARY KEY("id_user")
);


CREATE TABLE "user-role" (
	"id_role" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_user" INTEGER NOT NULL,
	PRIMARY KEY("id_role", "id_user")
);


CREATE TABLE "role" (
	"id_role" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR NOT NULL,
	PRIMARY KEY("id_role")
);

COMMENT ON TABLE "role" IS 'три роли. бухгалтер и шеф-повар и админ';


CREATE TABLE "order_composition" (
	"id_composition" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_product" INTEGER NOT NULL,
	"quntity_item" INTEGER NOT NULL,
	PRIMARY KEY("id_composition")
);


ALTER TABLE "products_recipes"
ADD FOREIGN KEY("id_recipes") REFERENCES "recipes"("id_recipes")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dishes_menu"
ADD FOREIGN KEY("id_dish") REFERENCES "dishes"("id_dish")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dishes"
ADD FOREIGN KEY("id_recipes") REFERENCES "recipes"("id_recipes")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dishes_menu"
ADD FOREIGN KEY("Id_menu") REFERENCES "menu"("id_menu")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "products_recipes"
ADD FOREIGN KEY("id_products") REFERENCES "products"("id_products")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "order_composition"
ADD FOREIGN KEY("id_product") REFERENCES "products"("id_products")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "purchase_order"
ADD FOREIGN KEY("id_composition") REFERENCES "order_composition"("id_composition")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user-role"
ADD FOREIGN KEY("id_role") REFERENCES "role"("id_role")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user-role"
ADD FOREIGN KEY("id_user") REFERENCES "user"("id_user")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "purchase_order"
ADD FOREIGN KEY("id_suppliers") REFERENCES "suppliers"("id_suppliers")
ON UPDATE NO ACTION ON DELETE NO ACTION;